/*
 * This Java source file was generated by the Gradle 'init' task.
 
import org.apache.tomcat.jni.Library;
import org.junit.Test;


public class LibraryTest {
    @Test public void testSomeLibraryMethod() {
        Library classUnderTest = new Library();
        assertTrue("someLibraryMethod should return 'true'", classUnderTest.someLibraryMethod());
    }
}
*/
